### PR TITLE
Bug: Erase booking content issues

### PR DESCRIPTION
**Pull request by mathvaillant**

### CODE REVIEW

**Comment by joaoqueiroz95** [comment]
I am not sure if this is enough to fix. What if you click "Logout"?

There are other ways to go back

**Comment by mathvaillant** [comment]
> I am not sure if this is enough to fix. What if you click "Logout"?
> 
> There are other ways to go back

That's true. Already fixed that!

**Comment by mathvaillant** [comment]
[BUG - Booking again after confirm doesn't reset](https://trello.com/c/ZvgzBqxJ/63-bug-booking-again-after-confirm-doesnt-reset)

**Comment by joaoqueiroz95** [comment]
LGTM

**Review by joaoqueiroz95 — APPROVED** [review]

**Pull request merged**
