### PR TITLE
2 Digits UI

### PR DESCRIPTION
**Pull request by joaoqueiroz95**
thowdig-22
twodig-33

### CODE REVIEW

**Review by mathvaillant — COMMENTED** [review]
I think you forgot to commit the changes that makes `1` become `01`

**Comment by joaoqueiroz95** [comment]
> I think you forgot to commit the changes that makes `1` become `01`

This should come from the API, I would say.
I forced a "0" to appear for the pictures. But without it is simply 1 digit centered

**Comment by mathvaillant** [comment]
> > I think you forgot to commit the changes that makes `1` become `01`
> 
> This should come from the API, I would say. I forced a "0" to appear for the pictures. But without it is simply 1 digit centered

I agree with you, but we should then check with David if they will change this to a string. Right now it comes as an integer `int32`. 

```
"Transportable": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "integer",
                        "format": "int32",
                        "example": 1
                    },
                    "code": {
                        "type": "string",
                        "example": "AD"
                    },
                    "name": {
                        "type": "string",
                        "example": "Adult"
                    }
                }
            },
```

**Comment by joaoqueiroz95** [comment]
> > > I think you forgot to commit the changes that makes `1` become `01`
> > 
> > 
> > This should come from the API, I would say. I forced a "0" to appear for the pictures. But without it is simply 1 digit centered
> 
> I agree with you, but we should then check with David if they will change this to a string. Right now it comes as an integer `int32`.
> 
> ```
> "Transportable": {
>                 "type": "object",
>                 "properties": {
>                     "key": {
>                         "type": "integer",
>                         "format": "int32",
>                         "example": 1
>                     },
>                     "code": {
>                         "type": "string",
>                         "example": "AD"
>                     },
>                     "name": {
>                         "type": "string",
>                         "example": "Adult"
>                     }
>                 }
>             },
> ```

Yes, makes sense. Maybe we wait for their API update?

**Review by joel-gouveia — APPROVED** [review]

**Comment by mathvaillant** [comment]
LGMT!

**Pull request merged**
